import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { AppFooter } from "@/components/app-footer";
import { AppHeader } from "@/components/app-header";
import { ThemeProvider } from "@/components/theme-provider";
import { TooltipProvider } from "@/components/ui/tooltip";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Marcello's website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={cn("font-sans antialiased", inter.variable)}
      suppressHydrationWarning
    >
      <body>
        <ThemeProvider>
          <TooltipProvider>
            <AppHeader />

            <main className="mx-auto flex max-w-4xl flex-1 flex-col gap-4 p-8">{children}</main>

            <AppFooter />
          </TooltipProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
